Hexlet/ru-test-assignments

README.md

Этот тест  делался сотрудниками Badoo, но это было скорее for fun. Это не тестовое задание на роль PHP-разработчика, мы не требуем проходить его перед собеседованием

Remove badoo -> http://php.feedme.ru/ as it is not badoo test assignment

---

README.md

Ряд изменений для повышения читаемости списка.

Удаление избыточности

---

README.md

Update some existing position

---

README.md

Добавил компанию Digital Dali и их тестовое на Junior Frontend разработчика

Digital Dali

---

README.md

Removed all irrelevant tasks, added some new ones, edited some inaccuracies.

update the list

---

README.md

add information about Hexlet + logo

---

README.md

Добавил тестовое задание от компании sendsay на позицию frontend-developer react.

add sendsay.ru react

---

README.md

Добавлены тестовые для Java и QA

update CSSSR vacancies

---

README.md

was deleted on https://github.com/Ecwid/new-job/commit/a454498262b84ffa6587769dbd190f2bd6296568
will fixed https://github.com/Hexlet/ru-test-assignments/issues/49

delete obsolete task

---

README.md

Привет!
Я — Саша, дизайнер продукта из Sendsay. Иногда я помогаю искать новых людей в свою команду.
У вас в доках были не самая новая ссылка на наши тестовые. Подумал, что смогу их немного обновить + у нас появилось новое тестовое задание (до официальной премьеры в HH.ru)
Буду рад, если эти обновления помогут вашим ученикам

update Sendsay vacancies

---

README.md

Add new task TMK

---

README.md

Ссылки на тестовые задания для backend и frontend разработчика.
#70

Тестовые задания Waliot

---

README.md

Add new task for php developers on laravel

Add new task for PHP

---

README.md

Added the test task from Poker Stars Group for Front end Developers. All tasks inside of the project.

Added Poker Stars test task

---

README.md

Добавил новое тестовое - Программист PHP - http://teoxoft.com/

Add new test assignment - TX Consulting

---

README.md

Added a new test task for the backend PHP from Greensight

added test task for the backend from greensight

---

README.md

Added a new test tasks for the backend and frontend from CS-Cart

[#88] added test tasks for the backend and frontend from cscart

---

README.md

add Matic Insurance Services  test assignment

add Matic Insurance Services  test assignment 

---

README.md

Добавлен новый раздел "Без компании" и одно тестовое задание в нем (_frontend test case_).

added new frontend test case (noname)

---

README.md

Ссылка на задание от ITSumma не работала по http и доступна только по httpS. Но глобально - не очень понятно что именно там является заданием.

Fix link for ITSumma

---

README.md

Добавил тестовое от компании Detego

added test task from Detego company

---

README.md

Обновлена ссылка на задания от Ivelum

Fix link for Ivelum

---

README.md

Удалены, так как доступ к ним закрыт

Delete Volt tests

---

README.md

Hi!
This is a new test with React for junior frontend-developer from RooX Solutions

add new frontend-developer test

---

README.md

Updating link to test assignment due to file deletion.
Closes #96

Update link for Versta

---

README.md

Добавлено тестовое задание от "Домотехники"

[#114] Domotekhnika task added

---

README.md

На данный момент, в проде преимущественно Vue 2

Уточнения по тестовому для Medods фронта

---

README.md

Газпромбанк, Армо

---

README.md

fix hexlet logo

---

README.md

Переходил по ссылке, чтобы проверить наличие макета. Он там отсутствует

add information about mockup design

---

README.md

Added two middle and junior level test tasks

Add Coin32 and NPO Farvater tasks

---

README.md

Removed links to non-existent tasks
(Both tasks give 404 error)

Delete CSSSR tasks

---

README.md

Add new test assignments for frontend and backend.

Add tasks from Oxem Studio

---

README.md

add test task

---

README.md

Возможно плагин prettier для vscode поломал. 
Перепроверил, сейчас лишних изменений нет

added three test assignments

---

README.md

Привет) Добавила пару тестов (Studika, Ютор)

added new tests

---

README.md

Добавлено тестовое задание для фронтендера в Екб-компанию Renue

add Renue (frontend-dev)

---

README.md

Добавил тестовое задание для вакансии фронтенд разработчик в Yoldi. Есть фигма и api описано в swagger

add Yoldi (frontend-dev)

---

README.md

Добавил тестовое задание в «СДК Гарант» на должность фронтенд разработчика. Для надежности текст тестового задания разместил в своем репозитории.

Add new task «СДК Гарант»

---

README.md

add: test task elasticsearch

---

README.md

убраны не рабочие ссылки, связано с #178

remove the broken links

---

README.md

Added test assignments for Hammer Systems and Cloud.ru

add assignments

---

README.md

add test-assigment from ООО 'МСтрой'
fix link for 'Монолит Северо-Запад' assigment
check links for python assigments

[#188] refresh python test-assigments

---

README.md

Добавлено 3 тестовых задания на позиции Стажера и Junior QA

New Test tasks

---

README.md

Добавил тз pixlpark: front, back, mobile

pixlpark tasks added

---

README.md

Add c# fullstack task

---

README.md

Добавлены в README.md 15 тестовых заданий, компании:
Учи.ру
Тинькоф
Табакон
Сравни.ру
Спортмастер
Совкомбанк Страхование
Северсталь
Сбербанк инженер данных
Самокат, аналитик
Самокат, аналитик
Роснефть, HR аналитик
Росмэн
Неизвестные (добавлены в секцию "без компании" как сборник тестовых"
МТС, продуктовый аналитик
МАРС , Аналитик данных

[#206] - ross_branch

---

README.md

Removing an invalid link

---

README.md

fundraiseup -> Backend test NodeJS
Ссылка на notion нерабочая.

[fundraiseup] Page not found

---

README.md

I grouped the tasks, there were a few unclear test ones left. I added them to the other folder. If something is wrong, write and I’ll fix it)

[#219] Group tasks by areas

---

README.md

All test tasks are automation QA. I didn't find chapter about this in the list. That's why i added tasks in 'Other'.
And i have a question. Are we need to add this [link with tasks](https://vladislaveremeev.gitbook.io/qa_bible/prakticheskaya-chast/primery-zadach-na-sobesedovaniyakh-i-testovykh-zadanii)? I'm not sure because it's not from GitHub and it's not from any company, just examples.

added 5 test tasks in chapter 'Other'

---

README.md

I also deleted duplicates for avito.tech Go tests and corrected the format of the list for avito.tech in Backend section.
Changes made as per issue #225

Move Go to a new section and Manual QA near to Automation QA

---

README.md

- Added some test assignments
- Removed unavailable test assignments
- Replaced and organized some test assignments in alphabetical order
The work was done as part of issue #188.

Fix Frontend test assignments

---

README.md

updated README.md - deleted non-working reference for C/C++ developer

Resolve issue #236
